





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;


namespace SitecoreBootstrap.SitecoreBootstrap.Web.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace SitecoreBootstrap.SitecoreBootstrap.Web.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Page</para>	
	/// <para>ID: 5fe0f2d8-ecbf-4d95-833c-07b4f6d3a568</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage : IGlassBase 
	{
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: bb60da63-4dcc-4931-9ce0-dcca49b27870</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IPageConstants{

			public const string TemplateIdString = "5fe0f2d8-ecbf-4d95-833c-07b4f6d3a568";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page";

					
			public static readonly ID TitleFieldId = new ID("bb60da63-4dcc-4931-9ce0-dcca49b27870");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Page</para>	
	/// <para>ID: 5fe0f2d8-ecbf-4d95-833c-07b4f6d3a568</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString)] //, Cachable = true
	public partial class Page  : GlassBase, IPage 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bb60da63-4dcc-4931-9ce0-dcca49b27870</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
